### ISSUE TITLE
Issue with private key size property loading

### ISSUE THREAD

**Issue by csviri** [quarkiverse/quarkus-cert-manager#26]
If I set 
`quarkus.certificate.privateKey.size=2048` in `application.properties` I receive an exception:

it seems to be is is not parsed correctly as an integer:

```text
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.certmanager.deployment.CertManagerProcessor#feature threw an exception: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.lambda$getOptionalInteger$16(CertificateConfigAdapter.java:190)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.getOptionalInteger(CertificateConfigAdapter.java:190)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.getCertificatePrivateKey(CertificateConfigAdapter.java:142)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.lambda$getCertificateConfig$2(CertificateConfigAdapter.java:75)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.getCertificateConfig(CertificateConfigAdapter.java:75)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.newBuilder(CertificateConfigAdapter.java:54)
	at io.quarkiverse.certmanager.deployment.CertManagerProcessor.configureDekorateToGenerateCertManagerResources(CertManagerProcessor.java:204)
	at io.quarkiverse.certmanager.deployment.CertManagerProcessor.feature(CertManagerProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 47 more
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.lambda$getOptionalInteger$16(CertificateConfigAdapter.java:190)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.getOptionalInteger(CertificateConfigAdapter.java:190)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.getCertificatePrivateKey(CertificateConfigAdapter.java:142)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.lambda$getCertificateConfig$2(CertificateConfigAdapter.java:75)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.getCertificateConfig(CertificateConfigAdapter.java:75)
	at io.dekorate.certmanager.adapter.CertificateConfigAdapter.newBuilder(CertificateConfigAdapter.java:54)
	at io.quarkiverse.certmanager.deployment.CertManagerProcessor.configureDekorateToGenerateCertManagerResources(CertManagerProcessor.java:204)
	at io.quarkiverse.certmanager.deployment.CertManagerProcessor.feature(CertManagerProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)


```

**Comment by csviri** [comment]
to reproduce it just run the build here: https://github.com/java-operator-sdk/kubernetes-webooks-framework/pull/49

**Comment by Sgitario** [comment]
@csviri In Quarkus, by default you need to provide the properties using the kebab format: 
```
quarkus.certificate.private-key.size=2048
```
You can see the full list of properties in the Quarkus CertManager extension documentation: https://quarkiverse.github.io/quarkiverse-docs/quarkus-certmanager/dev/index.html#quarkus-certificate_quarkus.certificate.private-key.size
